language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - bash

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install -y gcc g++ clang make bison flex automake autoconf libtool cmake; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install gcc make bison flex autoconf libtool; fi

script:
  - cd jxnet-native/libpcap && ./configure && make && cd ../..
  - cd jxnet-native && export JAVA_HOME=$(pwd) && ./bootstrap.sh && ./configure && make && sudo make install && cd ..
  - cd jxnet-native && mkdir build && cd build && cmake .. && make && sudo make install && cd ../..
  - cd jxnet-native/libpcap && sudo make install && cd ../..
