
language: java

jdk:
  - openjdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpcap-dev libpcap0.8 gcc

script:
  - echo "githubToken=$GITHUB_TOKEN" >> gradle.properties
  - ./gradlew -p jxnet-native clean build -q
  - sudo ./gradlew jacocoTestReport coveralls
