
trigger:
  - master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: "vs2017-win2016"
  maxParallel: 2

pool:
  vmImage: $(imageName)

variables:
  - group: TOKEN

steps:
  # Linux
  - bash: |
      sudo -E apt-get install libpcap0.8
      sudo -E ln -s /usr/lib/x86_64-linux-gnu/libpcap.so.1.7.4 /usr/lib/libpcap.so.1
      sudo -E ./gradlew -p jxnet-core assemble test
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: Linux Environment
  # MacOS
  - bash: |
      export JAVA_HOME=`/usr/libexec/java_home -v 1.8`; java -version
      sudo -E ./gradlew test jacocoTestReport
      sudo -E ./gradlew coveralls
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: Darwin Environment
  # Windows
  - powershell: |
      ./.scripts/InstallNpcap.ps1
      ./gradlew test jacocoTestReport
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f jxnet-core/build/reports/jacoco/test/jacocoTestReport.xml -t $env:CODECOV_TOKEN
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: Windows Environment
