
version: 2

jobs:
  build:
    working_directory: ~/Jxnet
    docker:
      - image: 'circleci/openjdk:8-jdk'
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: 'export TERM=xterm-color'
      - run: 'sudo apt-get update'
      - run: 'sudo apt-get -y install bash gcc g++ make git bison flex automake autoconf libtool cmake'
      - run: 'cd jxnet-native/libpcap && ./configure && make && cd ../..'
      - run: 'cd jxnet-native && export JAVA_HOME=$(pwd) && ./bootstrap.sh && ./configure && make && sudo make install && cd ..'
      - run: 'cd jxnet-native && mkdir build && cd build && cmake .. && make && sudo make install && cd ../..'
      - run: 'cd jxnet-native/libpcap && sudo make install && cd ../..'
      - run: './gradlew build -x test'
      - save_cache:
          key: gradle
          paths:
            - "~/.gradle"
  deploy:
    working_directory: ~/Jxnet
    docker:
      - image: 'circleci/openjdk:8-jdk'
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: 'export TERM=xterm-color'
      - run: 'sudo apt-get update && sudo apt-get install gcc libpcap-dev gnupg -y'
      - run: 'echo "githubToken=$GITHUB_TOKEN" >> gradle.properties'
      - run: 'echo "bintrayUser=$BINTRAY_USER" >> gradle.properties'
      - run: 'echo "bintrayPass=$BINTRAY_PASS" >> gradle.properties'
      - run: 'echo "sonatypeUser=$SONATYPE_USER" >> gradle.properties'
      - run: 'echo "sonatypePass=$SONATYPE_PASS" >> gradle.properties'
      - run: 'echo "signing.keyId=$SIGNING_KEY_ID" >> gradle.properties'
      - run: 'echo "signing.password=$SIGNING_PASS" >> gradle.properties'
      - run: 'echo "signing.secretKeyRingFile=/tmp/secring.gpg" >> gradle.properties'
      - run: 'gpg --batch --yes --passphrase=$SIGN_KEY --output /tmp/secring.gpg --decrypt --cipher-algo AES256 ./gradle/resources/gpg/secring.gpg.enc'
      - run: './gradlew clean build install bintrayUpload dist github -x test --no-daemon -q'
      - save_cache:
          key: gradle
          paths:
            - "~/.gradle"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - v1
      - build:
          filters:
            branches:
              only:
                - master
